apiVersion: v1
kind: Service
metadata:
  name: bluegreen-green-preview
  namespace: bluegreen-demo
  labels:
    app: bluegreen-demo
    role: preview
    version: green
spec:
  type: ClusterIP
  selector:
    app: bluegreen-demo
    version: green
  ports:
    - name: http
      port: 80
      targetPort: 80
