apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: canary-demo
  namespace: canary-demo
spec:
  parentRefs:
    - name: public-gateway
      namespace: platform-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: canary-stable
          port: 80
          weight: 0
        - name: canary-v2
          port: 80
          weight: 100
