apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-stable.yaml
  - configmap-canary.yaml
  - configmap-viewer.yaml
  - deployment-stable.yaml
  - deployment-canary.yaml
  - deployment-viewer.yaml
  - service-stable.yaml
  - service-canary.yaml
  - service-viewer.yaml
  - httproute.yaml
